version: "3.9"
services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - ${REDIS_PORT}:6379
  db:
    image: postgres:15-alpine
    volumes:
      - database:/data/db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
  api:
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DB_HOST: ${DB_HOST}
      REDIS_HOST: ${REDIS_HOST}
volumes:
  database:
