export default [
  {
    firstname: '',
    lastname: '',
    email: '',
    password: '',
    role: '',
  },
  {
    firstname: '',
    lastname: 'doe',
    email: 'johndoe@email.com',
    password: 'john12345',
    role: 'mentee',
  },
  {
    firstname: 'john',
    lastname: '',
    email: 'johndoe@email.com',
    password: 'john12345',
    role: 'mentee',
  },
  {
    firstname: 'john',
    lastname: 'doe',
    email: '',
    password: 'john12345',
    role: 'mentee',
  },
  {
    firstname: 'john',
    lastname: 'doe',
    email: 'johndoe@email.com',
    password: '',
    role: 'mentee',
  },
  {
    firstname: 'john',
    lastname: 'doe',
    email: 'johndoeemail',
    password: 'john12345',
    role: 'mentee',
  },
  {
    firstname: 'john',
    lastname: 'doe',
    email: 'johndoe@email.com',
    password: 'john12',
    role: 'mentee',
  },
  {
    firstname: 'john',
    lastname: 'doe',
    email: 'johndoe@email.com',
    password: 'john123456',
    role: 'mentee',
  },
  {
    firstname: 'john',
    lastname: 'doe',
    email: 'johndoe@email.com',
    password: 'john123456',
    role: '',
  },
  {
    firstname: 'doe',
    lastname: 'john',
    email: 'doejohn@email.com',
    password: 'doe123456',
    role: 'mentee',
  },
];
